version: "3.8"

services:
    app:
        build:
            context: .
        container_name: demo
        image: jenkins-asg-demo-site
        restart: always
        ports:
            - "80:80"
